[tool.poetry]
name = "findingthingswithpython"
version = "0.1.13"
description = ""
authors = ["Emil Merle"]

[tool.poetry.dependencies]
python = "^3.8"
pyperclip = "^1.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
